[package]
name = "ngrok"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "The ngrok agent SDK"
repository = "https://github.com/ngrok/ngrok-rs"

[lib]
name = "ngrok"
crate-type = ["cdylib", "rlib"]

[dependencies]
muxado = { path = "../muxado", version = "0.1.0" }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
thiserror = "1.0.37"
base64 = "0.13.1"
tokio = { version = "1.23.0", features = ["sync", "time"] }
tracing = "0.1.37"
async-rustls = { version = "0.3.0" }
tokio-util = { version = "0.7.4", features = ["compat"] }
futures = "0.3.25"
hyper = { version = "0.14.23", features = ["server"] }
axum = { version = "0.6.1", features = ["tokio"] }
rustls-pemfile = "1.0.1"
async-trait = "0.1.59"
bytes = "1.3.0"
arc-swap = "1.5.1"
tokio-retry = "0.3.0"
pyo3 = { version = "0.17.3", features = ["extension-module"] }
pyo3-asyncio = { version = "0.17", features = ["attributes", "tokio-runtime"] }
blocking = "0.4.7"

[build-dependencies]
prost-build = "0.11.3"
pyo3-build-config = "0.17.3"

[dev-dependencies]
anyhow = "1.0.66"
axum = "0.6.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
